{
  try {
    XQQueryException ex=new XQQueryException("Hello world!",new QName("foo"));
    junit.framework.Assert.assertEquals("A-XQQEX-1.1: XQQueryException successfully created","Hello world!",ex.getMessage());
    junit.framework.Assert.assertEquals("A-XQQEX-1.1: XQQueryException successfully created",new QName("foo"),ex.getErrorCode());
  }
 catch (  Exception e) {
    junit.framework.Assert.fail("A-XQQEX-1.1: Creating XQQueryException faild with message: " + e.getMessage());
  }
}
