{
  try {
    return input(ii).content();
  }
 catch (  final IOException ex) {
    throw error.thrw(ii,ex);
  }
}
