{
  try {
    XQQueryException ex=new XQQueryException("Hello world!");
    junit.framework.Assert.assertEquals("A-XQQEX-1.1: XQQueryException successfully created","Hello world!",ex.getMessage());
  }
 catch (  Exception e) {
    junit.framework.Assert.fail("A-XQQEX-1.1: Creating XQQueryException faild with message: " + e.getMessage());
  }
}
