{
  try {
    XQQueryException ex=new XQQueryException("Hello world!",new QName("foo"),7,8,56);
    assertEquals("A-XQQEX-1.1: XQQueryException successfully created","Hello world!",ex.getMessage());
    assertEquals("A-XQQEX-1.1: XQQueryException successfully created",new QName("foo"),ex.getErrorCode());
    assertEquals("A-XQQEX-1.1: XQQueryException successfully created",7,ex.getLineNumber());
    assertEquals("A-XQQEX-1.1: XQQueryException successfully created",8,ex.getColumnNumber());
    assertEquals("A-XQQEX-1.1: XQQueryException successfully created",56,ex.getPosition());
  }
 catch (  Exception e) {
    fail("A-XQQEX-1.1: Creating XQQueryException faild with message: " + e.getMessage());
  }
}
