{
  try {
    s.close();
  }
 catch (  final Exception ex) {
    throw new AssertionError(ex.toString());
  }
}
