{
  try {
    return method != null ? method.invoke(object,args) : null;
  }
 catch (  final Exception ex) {
    Util.debug(ex);
    return null;
  }
}
