{
  try {
    ready=true;
    return qp.next();
  }
 catch (  final Exception ex) {
    throw new BaseXException(ex);
  }
}
